### ISSUE TITLE
Node 4.0.0

### ISSUE THREAD

**Issue by omatvejev** [Ecotrust-Canada/scanthis#9]
Node 4.0.0 is marked as stable and has most of ecma6 class features available. I've tried this node version on my local machine and it seems like it's working well with our app. 

https://github.com/nodejs/node/blob/v4.0.0/CHANGELOG.md

@countable What do you think about this?

**Comment by countable** [comment]
Most of our code will be on the client, but may as well make use of these on the server.

**Comment by omatvejev** [comment]
We're now using node 4.0.0. Issue closed.
